services:
  # Backend Service
  - type: web
    name: hashpay-server
    env: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hashpay-db
          property: connectionString
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20.12.0
      - key: DB_DIALECT
        value: postgres

databases:
  - name: hashpay-db
    databaseName: hashpay
    user: hashpay_user
    plan: free

  # Frontend Service
  - type: web
    name: hashpay-web
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
